=== GIP-RECIA/esco-ws4Internet2Grouper/properties/export/sarapis-groups.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT sarapis-group-service (comment?, (folder|folder-template)+) >
<!ELEMENT folder (comment?, administrated-by?,(folder|folder-template|group|group-template)*) >
<!ELEMENT folder-template (comment?, administrated-by?,(folder|folder-template|group|group-template)*) >
<!ELEMENT group (comment?, administrated-by?, member-of*, members*) >
<!ELEMENT group-template (comment?, administrated-by?, member-of*, members*) >
<!ELEMENT comment ANY>
<!ELEMENT administrated-by ANY>
<!ELEMENT member-of ANY>
<!ELEMENT members ANY>


<!ATTLIST folder
	extension CDATA #REQUIRED
	display-extension CDATA #REQUIRED 
	description CDATA #REQUIRED
	preexisting CDATA #IMPLIED>

<!ATTLIST folder-template
	extension CDATA #REQUIRED
	display-extension CDATA #REQUIRED 
	description CDATA #REQUIRED>
	
<!ATTLIST group
	extension CDATA #REQUIRED
	display-extension CDATA #REQUIRED 
	description CDATA #REQUIRED
	preexisting CDATA #IMPLIED>
	
<!ATTLIST group-template
	extension CDATA #REQUIRED
	display-extension CDATA #REQUIRED 
	description CDATA #REQUIRED>
	
<!ATTLIST administrated-by
		  path CDATA #REQUIRED
		  recursive CDATA #IMPLIED>	
		  
<!ATTLIST member-of
		  path CDATA #REQUIRED>	

<!ATTLIST members
		  type CDATA #REQUIRED
		  distribution-by CDATA #IMPLIED>

=== GIP-RECIA/esco-ws4Internet2Grouper/properties/export/sarapis-groups-service.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sarapis-group-service SYSTEM "classpath:properties/export/sarapis-groups.dtd">

<sarapis-group-service>
	<comment> Paramétrage du module d'alimentation des groupes de Sarapis.</comment>
	
	<user uid="Aeg00000"/>
	<delete-empty-folders value="false"/>
	<delete-empty-groups value="true"/>
	
	<ordered-template-elements>  
		<comment>
				Valeurs pouvant être substituées
				dans les definitions de modèles de groupes, de dossiers, 
				de privileges d'administration, etc.
				Remarque: L'ordre de definition est important et car il intervient dans le
				processus d'évaluation des modèles.
        </comment>
		<template-element key="%UAI_ETAB%"/>
		<template-element key="%NOM_ETAB%"/>
		<template-element key="%NIVEAU%"/>
		<template-element key="%NOM_CLASSE%"/>
		<template-element key="%DESC_CLASSE%"/>
		<template-element key="%DISCIPLINE%"/>
	</ordered-template-elements>

	<folder extension="ESCO" 
            display-extension="ESCO-PORTAIL"
		    description="Racine ESCO-PORTAIL" 
            preexisting="true">

        <comment>Racine des groupes pour ESCO-Portail</comment>

		<administrated-by path=".:Admin:Centrale" recursive="true">
			<comment>
				Ce privilège d'administration sera positionné pour toute
				l'arborescence située sous ce dossier. 
				Remarques : 
			     	- Seuls les dossiers et groups créés par le module
			       	Sarapis sont pris en compte (attribut peexisting=false).
			     	- On utilise ici un chemin relatif mais le chemin absolu aurait également
			       	été correct : ESCO:Admin:Centrale.
			</comment>
		</administrated-by>

		<!--
			~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		        Arborescence d'administration 
			~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		-->
		<folder extension="Admin" 
                display-extension="Administration"
			    description="Racine des groupes d'administration"
			    preexisting="true">
			<group extension="Centrale"
				   description="Groupe des administrateurs centraux"
				   display-extension="Groupe d'administration centrale" 
                   preexisting="true" />
            
			<folder extension="Locale" 
                    display-extension="Administration locale"
				    description="Racine pour les groupes d'administration locale"
				    preexisting="false">

				<group-template extension="Admin_%NOM_ETAB%_%UAI_ETAB%"
					            display-extension="Administration établissement %NOM_ETAB%"
					            description="Administration locale pour l'établissement %NOM_ETAB%" />
			</folder>
		</folder>
	

		<!-- 
			~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		        Arborescence des groupes d'établissement 
		    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		-->
	    <folder extension="Etablissements" 
                display-extension="Etablissements"
		        description="Racine pour les groupes d'établissement"
		        preexisting="false">
		        
  	        <comment> Racine pour tous les groupes d'établissement. </comment>

		    <folder-template extension="%NOM_ETAB%_%UAI_ETAB%"
			                 display-extension="%NOM_ETAB%_%UAI_ETAB%"
			                 description="Racine pour les groupes de l'établissement %NOM_ETAB%">
			                 
                <administrated-by path="ESCO:Admin:Locale:Admin_%NOM_ETAB%_%UAI_ETAB%"/>
				                  
			    <folder-template extension="%NIVEAU%"
				                 display-extension="Niveau %NIVEAU%"
				                 description="Racine pour les groupes de niveau">
					<administrated-by path="ESCO:Admin:Locale:Admin_%NOM_ETAB%_%UAI_ETAB%"/>
					
				    <group-template extension="Profs_%NOM_CLASSE%"  
					                display-extension="Prof. %NOM_CLASSE%"
					                description="Enseignants de la classe %NOM_CLASSE%">
					                
					    <member-of path="..:Tous_%NOM_CLASSE%" />
					    <member-of path="ESCO:Etablissements:%NOM_ETAB%_%UAI_ETAB%:Profs" />
					    <members type="Teacher" distribution-by="%NOM_CLASSE%" />
					    
				    </group-template> 

				    <group-template extension="%NOM_CLASSE%" 
                                    display-extension="%NOM_CLASSE%" 
					                description="Elèves de la classe %NOM_CLASSE%">
					    <member-of path="..:Tous_%NOM_CLASSE%" />
					    <member-of path="..:..:Eleves" />
					    <members type="Student" distribution-by="%NOM_CLASSE%" />
					    
				    </group-template>

			        <group-template extension="Tous_%NOM_CLASSE%"
					                display-extension="Tous %NOM_CLASSE%"
					                description="Enseignants et élèves de la classe %NOM_CLASSE%" />
			    </folder-template>
			    
                <group extension="Profs" 
                       display-extension="Profs"
				       description="Enseignants de l'établissment %NOM_ETAB%">
				       <member-of path="..:Tous_%NOM_ETAB%" />
 		        </group>
				       
                <group extension="Eleves" 
                       display-extension="Elèves"
				       description="Elèves de l'établissment %NOM_ETAB%">
				       <member-of path="..:Tous_%NOM_ETAB%" />
 		        </group>
            
                <group extension="Adminstratifs" 
                       display-extension="Administratifs"
				       description="Personnel administratif de l'établissment %NOM_ETAB%">
				       <member-of path="..:Tous_%NOM_ETAB%" />
				       <members type="TOS" distribution-by="%NOM_ETAB%" />
 		        </group>
				       
                <group extension="TOS" 
                       display-extension="TOS"
				       description="Personnel TOS de l'établissment %NOM_ETAB%">
				       <member-of path="..:Tous_%NOM_ETAB%" />
				       <members type="TOS" distribution-by="%NOM_ETAB%" />
 		        </group>

 				<group extension="Parents" 
                       display-extension="Parents"
				       description="Parents des élèves de l'établissment %NOM_ETAB%">
				       <member-of path="..:Tous_%NOM_ETAB%" />
				       <members type="Parent" distribution-by="%NOM_ETAB%" />
 		        </group>				       

 				<group extension="Tous_%NOM_ETAB%" 
                       display-extension="Tous_%NOM_ETAB%"
				       description="Personnel, parents et élèves de l'établissment %NOM_ETAB%"/>
 		        
 		        
 		        <folder extension="Disciplines" 
                        display-extension="Disciplines"
		                description="Racine pour les groupes de disciplines"
		                preexisting="false">
		                
		            	<administrated-by path="ESCO:Admin:Locale:Admin_%NOM_ETAB%_%UAI_ETAB%"/>
		            	
		            	<group-template extension="%DISCIPLINE%" 
                        	            display-extension="%DISCIPLINE%" 
					        	        description="Enseignants - discipline %DISCIPLINE%">
					    	<members type="Teacher" distribution-by="%DISCIPLINE%" />
					    </group-template>
		                
                </folder>
 		        
		    </folder-template>
	    </folder>
    </folder>
</sarapis-group-service>

=== GIP-RECIA/esco-ws4Internet2Grouper/properties/export/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sarapis-group-service SYSTEM "sarapis-groups.dtd">

<sarapis-group-service>

	<comment> Paramétrage du module d'alimentation des groupes de Sarapis.</comment>

	<folder extension="ESCO" 
            display-extension="ESCO-PORTAIL"
		    description="Racine ESCO-PORTAIL" 
            preexisting="true">

        <comment>Racine des groupes pour ESCO-Portail</comment>

		<administrated-by 
             path="Etablissements:Admin:Centrale" 
             recursive="true"/>


		<folder extension="Admin" 
                display-extension="Administration"
			    description="Racine des groupes d'administration"
			    preexisting="true">

			<group extension="Centrale"
				   description="Groupe des administrateurs centraux"
				   display-extension="Groupe d'administration centrale" 
                   preexisting="true" />
            
			<folder extension="Locale" 
                    display-extension="Administration locale"
				    description="Racine pour les groupes d'administration locale"
				    preexisting="false">

				<group-template extension="Admin_%NOM_ETAB%_%UAI_ETAB%"
					            display-extension="Administration établissement %NOM_ETAB%"
					            description="Administration locale pour l'établissement %NOM_ETAB%" />

			</folder>

		</folder>
	

	    <folder extension="Etablissements" 
                display-extension="Etablissements"
		        description="Racine pour les groupes d'établissement"
		        preexisting="false">

		    <folder-template extension="%NOM_ETAB%_%UAI_ETAB%"
			                 display-extension="%NOM_ETAB% (%UAI_ETAB%)"
			                 description="Racine pour les groupes de l'établissement %NOM_ETAB%">
			                 
                <administrated-by path="ESCO:Etablissements:Admin:Admin_%NOM_ETAB%_%UAI_ETAB"
				                  recursive="true" />
				                  
			    <folder-template extension="%NIVEAU%"
				                 display-extension="Niveau %NIVEAU%"
				                 description="Racine pour les groupes de niveau">

				    

				    <group-template extension="Profs_%NOM_CLASSE%"  
					                display-extension="Prof. %NOM_CLASSE%"
					                description="Enseignants de la classe %NOM_CLASSE%">
					    <member-of path="ESCO:Etablissements:%NOM_ETAB%_%UAI_ETAB%:Tous_%NOM_CLASSE%" />
					    <member-of path="ESCO:Etablissements:%NOM_ETAB%_%UAI_ETAB%:Profs" />
					    <members type="Teacher" distribution-by="%NOM_CLASSE%" />
				    </group-template> 

				    <group-template extension="%NOM_CLASSE%" 
                                    display-extension="%NOM_CLASSE%" 
					                description="Elèves de la classe %NOM_CLASSE%">
					    <member-of path="Tous_%CLASSE %" />
					    <members type="Student" distribution-by="%NOM_CLASSE%" />
				    </group-template>

			        <group-template extension="Tous_%NOM_CLASSE%"
					                display-extension="Tous %NOM_CLASSE%"
					                description="Enseignants et élèves de la classe %NOM_CLASSE%" />
			    </folder-template>
			    
                <group extension="Profs" 
                       display-extension="Profs"
				       description="Enseignants de l'établissment %ETABLISSEMENT%" />

		    </folder-template>
	    </folder>
    </folder>
</sarapis-group-service>
